name: hello
on:
  push: 
    branches: [main]
  workflow_dispatch: 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello dosto"
      - name: sy hello to username
        run: echo "hello $USER"
  details:
      runs-on: ubuntu-latest
      steps:
        - name: version of python, docker, etc
          run: python --version && docker --version
